### ISSUE TITLE
[Bug]: JM Display Errors 1.7

### ISSUE THREAD

**Issue by brandyyn** [TeamJM/journeymap-legacy#18]
most biomes o plenty tall grass shows up as grey on the minimap if show plants is enabled
![image](https://github.com/TeamJM/journeymap/assets/11356565/42f99f5e-dd23-4540-b194-19364625bbd4)
![image](https://github.com/TeamJM/journeymap/assets/11356565/151188e9-3b84-4ca2-aacc-21d63154aa85)
![image](https://github.com/TeamJM/journeymap/assets/11356565/d67a4ca7-09b6-49b8-a02c-3d7fffea0e7e)

snow is also invisible on the minimap(but not always?) could be because i'm using journeymap, and it may only happen at certain altitudes since if i break the block below and place it 1 block lower it appears on the minimap but if i place the block above again and place the snow at the same altitude it was it doesnt show up again
![image](https://github.com/TeamJM/journeymap/assets/11356565/b5a15646-ebef-4f0b-94fb-f515f886695c)
![image](https://github.com/TeamJM/journeymap/assets/11356565/e69f827c-5982-4497-8367-1f7a9caa1ae0)
![image](https://github.com/TeamJM/journeymap/assets/11356565/3a9f6080-6ba8-406e-a061-935cd8029e85)
breaking the snow fixes it
![image](https://github.com/TeamJM/journeymap/assets/11356565/8baf4265-21d9-4b29-92a1-755ef8e0dbff)
![image](https://github.com/TeamJM/journeymap/assets/11356565/94ee18cb-dfdc-4299-8afd-43bf8d82a013)
![image](https://github.com/TeamJM/journeymap-legacy/assets/11356565/b16fb258-5e52-4585-8064-885e1a150a36)

using angelica a34
using journeymap 1.7.10 514p8 
BiomesOPlenty-1.7.10-2.1.0.1860-universal.jar
i am aware my bop is slightly out of date but its the last version to include some textures i like that were changed in later 1.7 versions.

**Comment by brandyyn** [comment]
![image](https://github.com/TeamJM/journeymap-legacy/assets/11356565/2c68591b-999a-4821-9362-cf17b9a50009)
tops of mushrooms are also invisible on the minimap.. wtf

**Comment by brandyyn** [comment]
<img width="1351" alt="image" src="https://github.com/TeamJM/journeymap-legacy/assets/11356565/6f7ecd29-e4d8-4ed5-8171-04ad8437f231">

the issue isnt fixed in the latest version 5.2.2, i don't have this problem in 5.1p6


<img width="1351" alt="image" src="https://github.com/TeamJM/journeymap-legacy/assets/11356565/028530ac-9bc6-4d7d-8568-650df1fb8070">

the bop handler also doesn't work for the tall grass still.. idk why this is an issue for bop but no other mod or grass type, i have so many flowers/plants/grass generating but the only ones that are grey are from bop

**Comment by brandyyn** [comment]
<img width="709" alt="image" src="https://github.com/TeamJM/journeymap-legacy/assets/11356565/1aca3cd9-00f2-4cc1-b402-5cfa37d879e5">
snow is fixed in latest release, 5.2.3, bop plants arent tho

**Comment by mysticdrew** [comment]
So to fix this, I likely will have to add each flower color manually. 
If you can get me a list of flower names and the hex color they should be, we can start getting them added and fixed. 
Join the discord and then we can work on getting some test builds until all flowers are done.

**Comment by mysticdrew** [comment]
Most of the issues have been addressed, however, the the list of bop plants and colors has not been provided and I will now be closing this issue as stale.
