### ISSUE TITLE
Make fairplay vs. unlimited a server-side config rather than having two separate client-side mods

### ISSUE THREAD

**Issue by dgealow** [TeamJM/journeymap-legacy#22]
It's very tedious to have to manually swap out a client-side mod in a modpack (e.g. GTNH) to either get to see other players and mobs on a server, or to comply with a server policy of not getting that. Architecturally, it would make much more sense to me for this to be a server-side setting--have a config file that determines whether players connecting to the server get the "unlimited" or "fairplay" experience.

**Comment by mysticdrew** [comment]
This was changed to just that in 1.12.2, I wont be doing it for legacy. Someone else can if they wish
