### ISSUE TITLE
Minimap cuts off on 1080p

### ISSUE THREAD

**Issue by Lyfts** [TeamJM/journeymap-legacy#36]
Started happening after https://github.com/TeamJM/journeymap-legacy/pull/35 and only seems to affect 1080p and below.

![jm_cut1](https://github.com/user-attachments/assets/4516bd12-9a74-4870-b444-733d7e2e81dd)
![jm_cut2](https://github.com/user-attachments/assets/8faab09b-ffa9-46ad-a76e-5f362f4e5023)

**Comment by mysticdrew** [comment]
Release should be out shortly.
