### ISSUE TITLE
MC can't show the Mod builded from my machine

### ISSUE THREAD

**Issue by thiagomaia971** [TeamJM/journeymap-legacy#8]
I downloaded the code, compiled and I get the "journeymap-1.7.10-5.9.4-fairplay.jar" and "journeymap-1.7.10-5.9.4-unlimited.jar", I paste this two files in my ".minecraft/mods" but when I load the mod is not recognize:
![image](https://user-images.githubusercontent.com/13563991/227698248-5f63626f-5715-40b0-8e91-06458e4b4e76.png)
![image](https://user-images.githubusercontent.com/13563991/227698266-1d822543-9934-46f4-b58b-d7121ee442fa.png)
![image](https://user-images.githubusercontent.com/13563991/227698278-e16bb092-3938-4bf2-93cc-6057beb4bd37.png)

**Comment by gdude2002** [comment]
Why are you trying to load two copies of the mod? Pick one of them.

**Comment by mysticdrew** [comment]
Maybe you should just download it from curseforge
